hw14 Домашнее задание №14 «Кроликизация Календаря»
VladimirButakov/hw-test pull request #16
Opened 2022-10-20 20:22 UTC by VladimirButakov

## Домашнее задание №14 «Кроликизация Календаря»

### Критерии оценки
- [ ] Makefile заполнен и пайплайн зеленый - 1 балл
- [ ] Работа с RMQ выделена в отдельный пакет, код не дублируется - 1 балл
- [ ] Реализован Рассыльщик - 2 балла
- [ ] Можно собрать сервисы одной командой (`make build`) - 1 балл
- [ ] Понятность и чистота кода - до 2 баллов

Реализован Планировщик:
- [ ] отсылает уведомления о выбранных событиях - 2 балла
- [ ] удаляет старые события - 1 балл

#### Зачёт от 7 баллов

2022-11-02 19:49 UTC, Nikscorp requested changes
Владимир, добрый день!

Работа хорошая, мне нравится стиль кода и лаконичность.
Я не совсем согласен с архитектурными решениями по части чтения и доставки событий, но замечания по ним не повлияют на оценку.

Основное критическое замечание сейчас из за которого я не могу принять работу — это неработоспособность sql части и частичное несоответствие контракта ТЗ. Подробности можно увидеть в комментариях к MR.

Прошу внести необходимые исправления.

2022-11-02 19:49 UTC, Nikscorp commented on hw12_13_14_15_calendar/Makefile
>  run: build
можно сделать отдельные цели для каждого бинаря

2022-11-02 19:49 UTC, Nikscorp commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +		fmt.Println(err)
почему не логгер?

2022-11-02 19:49 UTC, Nikscorp commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	err := s.db.Select(&result, "SELECT * FROM events WHERE notice_before != -1 AND date-notice_before BETWEEN $1 AND $2", fromTS, toTS)
мне кажется не очень хорошая идея смотреть between. Если у нас sender не работал какое-то время и мы его включили, то уведомления о старых событиях уже не отправится.

Но если это так и задумано, то наверное можно пропустить

2022-11-02 19:49 UTC, Nikscorp commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +func (s *Storage) GetEventsForNotification() ([]storage.Event, error) {
Для учебной реализации подойдет, но нужно понимать, что таких событий может быть очень много и:

- они могут не поместиться в память
- транзакция может быть очень дорогой и серьезно затормозить БД

Стоит подумать о работе батчами, может использовать гошные каналы, sql-ные курсоры (хотя можно и без них)

2022-11-02 19:49 UTC, Nikscorp commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	_, err = s.db.Exec("UPDATE events SET notice_before=-1 WHERE notice_before != -1 AND date-notice_before BETWEEN $1 AND $2", fromTS, toTS)
тут тоже не очень надежное решение — события считали, проставили им флаг отправки.

При этом приложение могло упасть и до отправки не дойти — таким образом нотификации будут потеряны.
Было бы здорово проставлять флажок уже после отправки в очередь

2022-11-02 19:49 UTC, Nikscorp commented on hw12_13_14_15_calendar/internal/amqp/producer/producer.go
> +		p.channel.Publish(
игнорируется ошибка. Более того для надежной отправки просто проверять ошибку недостаточно, подробнее в документации метода Publish

2022-11-02 19:49 UTC, Nikscorp commented on hw12_13_14_15_calendar/internal/scheduler/scheduler.go
> +			s.SendNotificationsToEvents(producer)
учитывая долгое время выполнения при большом объеме данных каждого из методов их следует выполнять в разных горутинах

2022-11-02 19:49 UTC, Nikscorp commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	err := s.db.Select(&result, "SELECT * FROM events WHERE notice_before != -1 AND date-notice_before BETWEEN $1 AND $2", fromTS, toTS)
плюс данный метод может работать сам по себе больше минуты (если в БД много данных) и просто пропускать события

2022-11-02 19:49 UTC, Nikscorp commented on hw12_13_14_15_calendar/Makefile
> +	$(BIN) -config ./configs/config.json
не нашел config.json или примера в репозитории

2022-11-02 19:49 UTC, Nikscorp commented on hw12_13_14_15_calendar/cmd/calendar_scheduler/main.go
> +	"github.com/streadway/amqp"
а как работает sql-ная часть без импорта драйвера? `_ "github.com/lib/pq"`

2022-11-02 19:49 UTC, Nikscorp commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	_, err := s.db.NamedExec("INSERT INTO events (id, title, date, duration_until, description, owner_id, notice_before) VALUES (:id, :title, :date, :duration_until, :description, :owner_id, :notice_bef
**Критическое замечание.**
Не работает `AddEvent`, получаю ошибку:

```
{
  "error": "13 INTERNAL: cannot create event, could not find name duration_until in &storage.Event{ID:\"8dfe5217-f669-42ba-b3a6-d530b1a0a5b1\", Title:\"Hello\", EventDate:20, Duration:0, Description:\"\", UserID:\"main_owner_id\", NoticeBefore:0}"
}
```

очень похоже, что sql часть не запускалась / не тестировалась.
Также замечу, что в контракте в добавлении события нет большинства полей — только название и дата, что несоответствует ТЗ. Просьба внести исправления

2022-11-02 23:37 UTC, VladimirButakov commented on hw12_13_14_15_calendar/Makefile
> +	$(BIN) -config ./configs/config.json
не закомитил, поправил

2022-11-02 23:38 UTC, VladimirButakov commented on hw12_13_14_15_calendar/cmd/calendar_scheduler/main.go
> +	"github.com/streadway/amqp"
хз как это потерялось, мб при правке линтера потёр

2022-11-02 23:38 UTC, VladimirButakov commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	_, err := s.db.NamedExec("INSERT INTO events (id, title, date, duration_until, description, owner_id, notice_before) VALUES (:id, :title, :date, :duration_until, :description, :owner_id, :notice_bef
поправил

2022-11-03 17:04 UTC, Nikscorp commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	_, err := s.db.NamedExec("INSERT INTO events (id, title, date, duration_until, description, owner_id, notice_before) VALUES (:id, :title, :date, :duration_until, :description, :owner_id, :notice_bef
Все так, но создаете то вы `rpc CreateEvent(ShortEvent) returns (Message)`, где в ShortEvent есть только title и date.

Но ок, допустим это можно потом заапдейтить, хотя это конечно не очень удобно

2022-11-03 17:21 UTC, Nikscorp commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	_, err := s.db.NamedExec("INSERT INTO events (id, title, date, duration_until, description, owner_id, notice_before) VALUES (:id, :title, :date, :duration_until, :description, :owner_id, :notice_bef
и в респонсе вы присылаете некий
```
{
  "message": "Created new"
}
```
а как клиенту узнать id? Сканить события?

В общем это однозначное снижение балла на мой взгляд.

2022-11-03 17:45 UTC, Nikscorp approved these changes
Владимир, добрый вечер!

Решение стало лучше, теперь SQL реализация работает — можно увидеть посылку сообщений, это хорошо.

Заметил, что перепутаны cmd для sender и sheduler и комментарии по дизайну API.
По этим замечаниям отнимаю 1 балл по критерию "понятность и чистота кода".

Текущая оценка: 9 баллов

2022-11-03 17:45 UTC, Nikscorp commented on hw12_13_14_15_calendar/cmd/calendar_scheduler/main.go
> +	c := simpleconsumer.New(config.AMPQ.Name, conn, logg)
scheduler и sender перепутаны местами в cmd

2022-11-04 11:17 UTC, VladimirButakov commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	_, err := s.db.NamedExec("INSERT INTO events (id, title, date, duration_until, description, owner_id, notice_before) VALUES (:id, :title, :date, :duration_until, :description, :owner_id, :notice_bef
А где в тз написано что клиент должен знать id обытия, вы на ходу требования сочиняете новые???

2022-11-04 11:37 UTC, VladimirButakov commented on hw12_13_14_15_calendar/cmd/calendar_scheduler/main.go
> +	c := simpleconsumer.New(config.AMPQ.Name, conn, logg)
поправил

2022-11-04 12:46 UTC, Nikscorp commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	_, err := s.db.NamedExec("INSERT INTO events (id, title, date, duration_until, description, owner_id, notice_before) VALUES (:id, :title, :date, :duration_until, :description, :owner_id, :notice_bef
Смотрите, в методы update и delete нужно передавать id, чтобы указать какое событие нужно менять. Если не возвращать id при создании события — клиент не сможет его узнать.

В ТЗ представлено верхнеуровневое описание, а не формальные требования.

2022-11-04 12:57 UTC, VladimirButakov commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	_, err := s.db.NamedExec("INSERT INTO events (id, title, date, duration_until, description, owner_id, notice_before) VALUES (:id, :title, :date, :duration_until, :description, :owner_id, :notice_bef
Ну бред на самом деле, из палца высасано, проектировать в домашней работе бизнес логику абстрактоного клиента, что он там должен и тд

2023-05-30 17:28 UTC, merged