Hw03 frequency analysis
VladimirButakov/hw-test pull request #4
Opened 2022-06-21 19:45 UTC by VladimirButakov

## Домашнее задание №3 «Частотный анализ»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-06-22 14:34 UTC, agneum requested changes
Спасибо за выполненное задание.
Хорошая работа, однако не хватает новых юнит-тестов, поэтому возвращаю решение на доработку

Итого: 6 баллов из 10

2022-06-22 14:34 UTC, agneum commented on hw03_frequency_analysis/top.go
> +	sortSlice := []element{}
Предлагаю указать capacity, чтобы уменьшить количество аллокаций при добавлении элементов в слайс

2022-06-22 14:34 UTC, agneum commented on hw03_frequency_analysis/top.go
> +	for _, value := range sortSlice {
Что возвращается на каждой итерации в качестве первого значения?

2022-06-22 17:03 UTC, VladimirButakov commented on hw03_frequency_analysis/top.go
> +	for _, value := range sortSlice {
++++

2022-06-23 10:32 UTC, agneum approved these changes
Спасибо за правки и тесты.
Принято: 10/10

2022-07-01 15:43 UTC, merged